name: Systest

on:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  start-vm:
    name: Start VM
    runs-on: trampoline
    outputs:
      label: ${{ steps.start-yc-runner.outputs.label }}
      instance-id: ${{ steps.start-yc-runner.outputs.instance-id }}
    steps:
      - name: Start YC runner
        id: start-yc-runner
        uses: yc-actions/yc-github-runner@v1
        with:
          mode: start
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          folder-id: b1gcvl619mdunf1cqqbv
          image-id: fd8ref8pd2uefi7o6kh3
          zone-id: 'ru-central1-b'
          subnet-id: e2lno1rkqo63l729dlo7
          cores: 16
          memory: 32GB
          core-fraction: 100
          disk-type: network-ssd-nonreplicated
          disk-size: 93GB

  checkout:
    name: Checkout sources
    needs: start-vm
    runs-on: ${{ needs.start-vm.outputs.label }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

  check:
    name: Run checks
    needs:
      - start-vm
      - checkout

    runs-on: ${{ needs.start-vm.outputs.label }}
    steps:
      - name: Kube cluster get credentials
        shell: bash
        run: |
          echo '${{ secrets.YC_SA_JSON_CREDENTIALS }}' > sa.json
          /usr/local/bin/yc config set service-account-key sa.json
          /usr/local/bin/yc managed-kubernetes cluster get-credentials --id catam8govqco1ladv4gv --internal --force
          bash yt/docker/yt_nightly/namespace.sh --invocation_id ${INVOCATION_ID} > /root/ns

      - name: Start YT and run systest
        shell: bash
        run: |
          export HOME=/root
          bash yt/docker/yt_nightly/cluster.sh --namespace $(cat /root/ns) --ytsaurus-source-path $(pwd)

  shutdown-cluster:
    name: Shutdown YT
    needs:
      - start-vm
      - check

    runs-on: ${{ needs.start-vm.outputs.label }}
    if: ${{ always() }}
    steps:
      - name: Shutdown YT
        shell: bash
        run: |
          export HOME=/root
          bash yt/docker/yt_nightly/shutdown_cluster.sh --ytsaurus-source-path $(pwd) --namespace $(cat /root/ns)

  stop-vm:
    name: Stop VM
    needs:
      - start-vm
      - check
      - shutdown-cluster
    runs-on: trampoline
    if: ${{ always() }}
    steps:
      - name: Stop YC runner
        uses: yc-actions/yc-github-runner@v1
        with:
          mode: stop
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-vm.outputs.label }}
          instance-id: ${{ needs.start-vm.outputs.instance-id }}

  send-notifications:
    name: Send notifications
    needs:
      - stop-vm
    runs-on: trampoline
    if: ${{ failure() }}
    steps:
      - name: Send telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          disable_web_page_preview: true
          format: markdown
          message: |
            Workflow *${{github.workflow}}* failed: ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}. Commit:
            ```
            ${{github.event.head_commit.message}}
            ```

